- hosts: all
  remote_user: root

  tasks:
  
  - name: apt is up-to-date 
    apt:
      update_cache: yes

  - name: locales is installed
    apt:
      name: locales
      state: latest

  - name: same locale
    copy:
      src: '/etc/locale.gen'
      dest: '/etc/locale.gen'

  - name: run locale-gen
    shell: 'locale-gen'

  - name: sudo is installed
    apt:
      name: sudo
      state: latest
 
  - name: git is installed
    apt:
      name: git
      state: latest
 
  - name: powerline-fonts is installed
    apt:
      name: fonts-powerline
      state: latest
 
  - name: zsh is installed
    apt:
      name: zsh
      state: latest

  - name: z.sh is installed
    get_url:
      url: "https://raw.githubusercontent.com/rupa/z/master/z.sh"
      dest: "/usr/local/bin"
      mode: 0775 
 
  - name: oh-my-zsh is installed
    git:
      repo: 'https://github.com/robbyrussell/oh-my-zsh'
      dest: '/root/.oh-my-zsh'

  - name: root-user has zsh-default-shell
    user: 
      name: root
      shell: /bin/zsh
      state: present

  - name: default-user is created
    user: 
      name: cite
      shell: /bin/zsh
      state: present
      createhome: yes
      groups: "sudo"
  
  - name: ssh-key of this machine is present
    authorized_key:
      user: cite
      state: present
      key: "{{ lookup('file', '/home/cite/.ssh/id_rsa.pub') }}"
  
- hosts: all
  remote_user: cite

  tasks:

  - name: oh-my-zsh is installed
    git:
      repo: 'https://github.com/robbyrussell/oh-my-zsh'
      dest: '~/.oh-my-zsh'

  - name: .zshrc is present
    get_url:
      url: 'https://raw.githubusercontent.com/atarax/shelltools/master/zshrc'
      dest: '/home/cite/.zshrc'


