- hosts: ansible_master
  remote_user: root

  tasks:

  - name: apt is up-to-date
    apt:
      update_cache: yes

  - name: git is installed
    apt:
      name: git
      state: latest
  
  - name: curl is installed
    apt:
      name: curl
      state: latest

  - name: shelltools (for .zshrc) is present
    git:
      repo: 'https://github.com/atarax/shelltools.git'
      dest: /root/shelltools
      update: yes

  - name: latest z-release is downloaded
    shell: curl https://raw.githubusercontent.com/rupa/z/master/z.sh > z.sh && chmod +x z.sh && mv z.sh /usr/local/bin

- hosts: all
  remote_user: root

  tasks:

  - name: apt is up-to-date 
    apt:
      update_cache: yes

  - name: zsh is installed
    apt:
      name: zsh
      state: latest

  - name: powerline-fonts is installed
    apt:
      name: fonts-powerline
      state: latest

  - name: oh-my-zsh is installed
    git:
      repo: 'https://github.com/robbyrussell/oh-my-zsh'
      dest: '~/.oh-my-zsh'

  - name: .zshrc is in current state
    copy:
      src: '/root/shelltools/zshrc'
      dest: '~/.zshrc'

  - name: z is installed
    copy:
      src: /usr/local/bin
      dest: /usr/local/bin

  - name: default-shell is zsh
    shell: chsh -s /bin/zsh
