- name: Download helm
  get_url: 
    url: "https://kubernetes-helm.storage.googleapis.com/helm-v2.8.0-linux-amd64.tar.gz"
    dest: /tmp/helm.tar.gz

- file: path=/tmp/helm state=directory

- name: Extract helm
  unarchive:
    src: /tmp/helm.tar.gz
    dest: /tmp/helm
    remote_src: yes

- name: Copy helm binary
  copy:
    src: /tmp/helm/linux-amd64/helm
    dest: "/usr/local/bin"
    owner: root
    group: root
    mode: 0755
    remote_src: True

- name: Create helm-serviceaccount 
  shell: "kubectl create serviceaccount --namespace kube-system tiller"

- name: Create helm-clusterrolebinding
  shell: "kubectl create clusterrolebinding tiller-cluster-rule --clusterrole=cluster-admin --serviceaccount=kube-system:tiller"

- name: Init helm
  shell: "/usr/local/bin/helm init --service-account tiller --force-upgrade"

- name: Copy istio.yaml
  copy:
    src: istio.yaml
    dest: /tmp/istio.yaml

- name: Install istio
  shell: "kubectl apply -f /tmp/istio.yaml"